version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./lib:/app/lib
    command: mix phx.server
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
